[package]
name = "retro-dev"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
clap.workspace = true
retro-format-v4.workspace = true

[dev-dependencies]
retro-engine = { path = "../retro-engine" }
retro-io.workspace = true
