[package]
name = "retro-audio"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
blake3.workspace = true
lewton.workspace = true
retro-platform = { path = "../retro-platform", default-features = false }
thiserror.workspace = true
