#include <math.h>
#include <stdio.h>

#ifndef M_PI
#define M_PI 3.14159265358979323846264338327950288
#endif

static int sinM7[0x200], cosM7[0x200];
static int sin512[0x200], cos512[0x200];
static int sin256[0x100], cos256[0x100];

static void print_array(FILE *f, const char *name, const int *a, int n)
{
    fprintf(f, "pub static %s: [i32; %d] = [", name, n);
    for (int i = 0; i < n; ++i) {
        if (i % 16 == 0)
            fprintf(f, "\n    ");
        fprintf(f, "%d, ", a[i]);
    }
    fprintf(f, "\n];\n\n");
}

int main(int argc, char **argv)
{
    if (argc != 2) {
        fprintf(stderr, "usage: %s <output.rs>\n", argv[0]);
        return 2;
    }

    for (int i = 0; i < 0x200; ++i) {
        sinM7[i] = (int)(sin((i / 256.0) * M_PI) * 4096.0);
        cosM7[i] = (int)(cos((i / 256.0) * M_PI) * 4096.0);
    }
    cosM7[0x00] = 0x1000;
    cosM7[0x80] = 0;
    cosM7[0x100] = -0x1000;
    cosM7[0x180] = 0;
    sinM7[0x00] = 0;
    sinM7[0x80] = 0x1000;
    sinM7[0x100] = 0;
    sinM7[0x180] = -0x1000;

    for (int i = 0; i < 0x200; ++i) {
        sin512[i] = (int)(sinf((i / 256.0) * M_PI) * 512.0);
        cos512[i] = (int)(cosf((i / 256.0) * M_PI) * 512.0);
    }
    cos512[0x00] = 0x200;
    cos512[0x80] = 0;
    cos512[0x100] = -0x200;
    cos512[0x180] = 0;
    sin512[0x00] = 0;
    sin512[0x80] = 0x200;
    sin512[0x100] = 0;
    sin512[0x180] = -0x200;

    for (int i = 0; i < 0x100; ++i) {
        sin256[i] = sin512[i * 2] >> 1;
        cos256[i] = cos512[i * 2] >> 1;
    }

    FILE *f = fopen(argv[1], "w");
    if (!f) {
        perror(argv[1]);
        return 1;
    }
    fprintf(f, "// Generated by tools/gen_math_tables.sh from the RSDKv4-Decompilation trig table\n");
    fprintf(f, "// formulas (RSDKv4/Math.cpp). Do not edit by hand; run the script to regenerate.\n\n");
    print_array(f, "SIN_M7_LOOKUP", sinM7, 0x200);
    print_array(f, "COS_M7_LOOKUP", cosM7, 0x200);
    print_array(f, "SIN_512_LOOKUP", sin512, 0x200);
    print_array(f, "COS_512_LOOKUP", cos512, 0x200);
    print_array(f, "SIN_256_LOOKUP", sin256, 0x100);
    print_array(f, "COS_256_LOOKUP", cos256, 0x100);
    fclose(f);
    return 0;
}
